### ISSUE TITLE
Raspberry Pi 3 Model A+

### ISSUE THREAD

**Issue by mkreisl** [AndrewFromMelbourne/raspberry_pi_revision#3]
Any chance to get an updated version, for the new model 3A+?

Thanks in advance

**Comment by AndrewFromMelbourne** [comment]
Yes. Sorry I didn't do it sooner. I will try to do it today.

**Comment by AndrewFromMelbourne** [comment]
OK done.

**Comment by mkreisl** [comment]
Wow, you're sooo fast

Thank you very much!
