### ISSUE TITLE
No revision match for new Raspberry Pi 4 Model B Rev 1.5

### ISSUE THREAD

**Issue by clanganke** [AndrewFromMelbourne/raspberry_pi_revision#8]
Hi Andrew,

I find your little programs quite useful, am using them since 2017 :-)

Just wanted to let you know that in the version of current master, `./table` does not show a quite new revision of a current RP4 model.
Moreover, there is a mismatch between `/proc/cpuinfo` and `./test`.

Output of `/proc/cpuinfo` is
```
Hardware        : BCM2835
Revision        : c03115
Serial          : 10000000f8b73778
Model           : Raspberry Pi 4 Model B Rev 1.5
```
Output of `./test`  does not match CPU and model name of CPU info, but correctly reports manufacturer and RAM
```
memory: 4096 MB
processor: Broadcom BCM2711
i2cDevice: /dev/i2c-1
model: Raspberry Pi 4 Model B
manufacturer: Sony UK
pcb revision: 5
warranty void: no
revision: c03115
peripheral base: 0xFE000000
```

I have got viewed the code, but did not get through it deep enough to feel save to extend it by the required data without breaking sth. 
Otherwise I would have tried and put a pull request...

**Comment by AndrewFromMelbourne** [comment]
Hi @clanganke. I believe that the cpuinfo is not correct. From memory I read somewhere that it reports the wrong processor for the Raspberry Pi. The BCM2835 was the original CPU on the very first Raspberry Pi.

If you look at the Raspberry Pi documentation, you will see that the Raspberry Pi 4 uses a Broadcom BCM2711.

https://www.raspberrypi.com/products/raspberry-pi-4-model-b/specifications/

Also, look at this thread in the Raspberry Pi forum

https://forums.raspberrypi.com/viewtopic.php?t=211658

**Comment by clanganke** [comment]
Hi Andrew,

I fully agree that the BCM2711 is the correct CPU. 

Just wanted to let you know that there is a new revision 1.5 in the wild, so that you could add it to your code for your programs, if it was intended anyway to keep the table complete.

Until now a script of mine scanned the output of your table program and there this revision is missing. I think I modify the script to use your `test` program, since the memory and the model are relevant to my set of script - here, 'Raspberry Pi 4 Model B' perfectly does the trick. So I am just very fine with your little progs and say: Thank you very much!
